# Welcome to ML!
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# Website settings
title: "ML"
description: "Miloud Lacheheb's blog, Big data and economics."
keywords: "Miloud, Lacheheb, blog, big data, economics"
baseurl: "/Miloud_Lacheheb" # Subpath as homepage (e.g., '/homepage')
url: "https://miloulach.github.io/Miloud_Lacheheb/" # URL should match your GitHub Pages URL

# Author -- index page "about me" section
author:
  name: "ML" # Used for blog posts' author
  first_name: "Miloud" # Used at index page about me section
  last_name: "Lacheheb" # Used at index page about me section
  avatar: "/static/assets/img/landing/avatar.jpg" # Upload your avatar and adjust path if needed
  github_username: "miloulach"
  linkedin_id: "miloud-lacheheb"
  twitter_username: "miloulach"
  email: "" # Leave blank if not available
  cv: "" # An online CV if available
  skill_icon1:
    - name: "icon-apache"
    - name: "fa-linux"
  skill_icon2:
    - name: "fa-linux"
    - name: "icon-apache"
  desc: "Experienced economist and data analyst specializing in climate change impact and extreme weather event modeling. Currently a PhD candidate in Economics at Victoria University of Wellington. Author of peer-reviewed publications in reputable journals such as the journal of Science of The Total Environment. Skilled in advanced statistical analysis, geospatial modeling, and data visualization using R, Python, and ArcGIS Pro."

# Comment
disqus:
  name: "ML"

# Analytics
## Google Analytics
ga:
  id: "UA-93473370-3"

## Google Optimize
go:
  id: ""

## GrowingIO
gio:
  id: ""

## Donation
donation: "off" # Set 'on'/'off' to display donation button on post pages

## Carousels
index_carousel: "on" # Index page carousel switch
blog_carousel: "on" # Blog page carousel switch

# SCSS
sass:
  style: "compressed"

# Build settings
encoding: "utf-8"

# Other settings
highlighter: "rouge"
markdown: "kramdown"
kramdown:
  input: "GFM"
  syntax_highlighter: "rouge"