---
title: "Interactive  map of Algeria"
author: " Miloud Lacheheb"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
runtime: shiny
---

```{r message=FALSE, warning=FALSE, include=FALSE}
library(sp)
library(mapdata)
library(ggmap)
library(rgdal)
library(sf)
library(RColorBrewer)
library(raster)
library(mapview)
library(spdep)
library(leaflet)
library(tmap)
library(Rmisc)
library(maptools)
library(rgeos)
```


```{r eruptions, include=FALSE}
alg<-readRDS("gadm36_DZA_1_sp.rds")
alg1<-st_as_sf(alg)
library(readr)
rawdata<-read_csv("ShinyAlg.csv")
algdata <- raster::merge(alg1, rawdata, by = "CC_1")

```



```{r message=FALSE, warning=FALSE, include=FALSE}
library(shiny)
library(ggiraph)
library(mapview)
library(leaflet)
ui = shinyUI(
  # Use a fluid Bootstrap layout
  fluidPage(
    # Give the page a title
    titlePanel("Map of Algeria"),
   
   sidebarLayout(
      
      
       #Sidebar panel for inputs 
      sidebarPanel(
        
         #First input: Type of data
       selectInput(inputId = "variableselected",
                   label = "Choose indicator:",
                    choices = colnames(algdata[13:14]), selected = "population")
    
  ),
  mainPanel(leafletOutput("map",height = 700))
  
)))
    
  
  # Define the server
server =shinyServer(function (input, output) {
  pal <- colorBin("YlOrRd", domain = NULL, pretty = TRUE)
  
  output$map<- renderLeaflet({
    #bins <- 7
    labels <- sprintf(
      "<strong>%s</strong><br/>%s",
      algdata$CC_1, algdata$wilaya
    ) %>% 
      lapply(htmltools::HTML)
    
    leaflet(algdata) %>% addTiles()%>%
      addPolygons(stroke = FALSE, #fillOpacity = .8,
                  smoothFactor = 0.2, label = labels,
                  #fillColor = ~pal(algdata$population),
                  weight = 2,
                  opacity = 1,
                  color = ~pal(eval(as.symbol(input$variableselected))),
                  dashArray = "3",
                  highlight = highlightOptions(
                    weight = 5,
                    color = "YlOrRd",
                    dashArray = "",
                    fillOpacity = 0.7,
                    bringToFront = TRUE))  %>% 
      addLegend(pal = pal, values = "color", position = c("bottomright"), opacity = 0.7, title = input$variableselected)
  })})

```


```{r echo=FALSE}
shinyApp(ui = ui, server = server)
```
